### ISSUE TITLE
Token page issues

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#612]
https://www.notion.so/blockscout/Token-contract-page-review-f8be8a59b3e14093a874a3025e105f41?pvs=4

- [x] Token instance from token transfers > 404 - wait for #592
- [x] Token page > Contract tabs are missing - wait for #596
- [x] Token page freezes sometimes, browser not responding  - that's the issue with ERC-1155 batches https://github.com/blockscout/blockscout/issues/6919
- [x] Missing token type labels - #470
- [x] Max total supply is zero sometimes - https://github.com/blockscout/blockscout/issues/6920
- [x] inventory: Pagination doesn’t work (pages do not change) - #613
- [x] Page jumps when switching to the next page -#614
