### ISSUE TITLE
Contract page issues

### ISSUE THREAD

**Issue by ulyanas** [blockscout/frontend#619]
https://www.notion.so/blockscout/Contract-page-review-abd2cf68de50420398d7042f8b1f299b?pvs=4

- [x] Coin balance history tab never loads data - https://github.com/blockscout/blockscout/issues/6926
- [x]  Logs tabs doesn’t load - https://github.com/blockscout/blockscout/issues/6928
- [x] minor UI issues will be fixed here - #621
- [x] UML diagram > 500 error - update staging config
- [x] Let’s add some free space below all short tables? It’s quite inconvenient to read data in the very bottom of the screen. Usually some extra space is added for better experience  - #623

part 2
https://www.notion.so/blockscout/Contract-verification-review-d8cea5968c654b21b0ddb52942a7b5fa
- [x] Two entries for the same address 0x97a4ab97028466FE67F18A6cd67559BAABE391b8 are displayed in the search, with the same link - https://github.com/blockscout/blockscout/issues/6971
- [x] Contract search is extremely slow now(>2min) - https://github.com/blockscout/blockscout/issues/6983
- [x] When verifying the contract, I saw a green notification that all was well and the contract was verified, but the spinner did not disappear and I was not redirected anywhere. - #665 
- [x] Return type with nested structures results in "HTTP 500, Internal server error” - https://github.com/blockscout/blockscout/issues/6964
- [x] On the contract source page, a ctrl-f search does not work well if the function you are looking for is not at the beginning of the file. - #664 
- [x] The "copy to clipboard" button can be handy near the addresses in the return values. - #665 
- [x] Numbers with lots of zeros that have to be entered manually in the numeric fields all the time. It would be cool to have some kind of shortcut for entering numbers like 10**18 - #607 
- [ ]  In addition to the name of the arguments in abi, there are also natspec comments from the contract developers in the source code. These would also be nice to display if possible. [Example](https://eth-goerli.blockscout.com/address/0x97a4ab97028466FE67F18A6cd67559BAABE391b8?tab=write_proxy). - https://github.com/blockscout/blockscout/issues/6984
- [x] There is no point in showing return type for write methods, because we will not get or see this result anyway - #665 
- [ ] messages about verfification
